name: TDR Tag and pre deploy Transfer Service
on:
  push:
    branches:
      - main
jobs:
  pre-deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/ecs_build.yml@main
    with:
      java-version: '17'
      repo-name: tdr-transfer-service
      image-name: transfer-service
      build-command: |
        sbt assembly
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=${{ needs.pre-deploy.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
