name: TDR Run Transfer Service tests
on:
  pull_request:
  push:
    branches-ignore:
      - main
      - release-*
permissions:
  id-token: write
  contents: write
jobs:
  test:
    uses: nationalarchives/tdr-github-actions/.github/workflows/tdr_test.yml@63eaeb7a4c65080f2a36ac88693fce04005c5a98 # v0.0.16
    with:
      repo-name: tdr-transfer-service
      test-command: |
        sbt scalafmtCheckAll test
      java-version: '17'
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
